apiVersion: v1
kind: Service
metadata:
  name: phonebook-service
  labels:
    name: phonebook-service
spec:
  type: NodePort
  selector:
    app: phonebook-app-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001